name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
        - 2.4
        - 2.5
        - 2.6
        - 2.7
        - 3.0
        - 3.1
        - jruby-9.1
        - jruby-9.2
        - jruby-9.3
        sidekiq-version:
        - 3.5
        - 4.2
        - 5.1
        - 5.2
        - 6.0
        # - 6.1
        # - 6.2
        # - 6.3
        # - 6.4
        # - 6.5
        - main
        exclude:
        # sidekiq 3.5 does not work with ruby >= 3
        - ruby-version: 3.0
          sidekiq-version: 3.5
        - ruby-version: 3.1
          sidekiq-version: 3.5
        # sidekiq 6+ only supports ruby >= 2.5
        - ruby-version: 2.4
          sidekiq-version: 6.0
        - ruby-version: 2.4
          sidekiq-version: main
        - ruby-version: jruby-9.1
          sidekiq-version: 6.0
        - ruby-version: jruby-9.1
          sidekiq-version: main
    services:
      redis:
        image: redis
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
        - 6379:6379
    env:
      sidekiq: ${{ matrix.sidekiq-version }}
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
      timeout-minutes: 5
    - name: Run tests
      run: bundle exec rake
      continue-on-error: ${{ matrix.sidekiq-version == 'main' }}
      timeout-minutes: 5
    - name: Report code coverage
      if: ${{ github.ref == 'refs/heads/master' && matrix.ruby-version == '3.1' && matrix.sidekiq-version == '6.0' }}
      continue-on-error: true
      uses: paambaati/codeclimate-action@v3.0.0
